language: rust
rust:
  - stable
  - nightly

sudo: false

notifications:
  email: false

script:
  - rustup default stable
  - cargo clean
  - cargo check --verbose --examples
  - cargo check --no-default-features
  - cargo check --no-default-features --features="multithreading"
  - cargo test
  - rustup default nightly
  - rustup target add wasm32-unknown-unknown
  - cargo +nightly check --no-default-features --target wasm32-unknown-unknown