language: rust

rust:
  - stable

sudo: false

notifications:
email: false

script:
  - cargo check --verbose --examples
  - cargo check --no-default-features
  - cargo check --no-default-features --features="multithreading"
  - cargo check --no-default-features --target wasm32-unknown-unknown
  - cargo test